### PR TITLE
fix: improve get headers from request #2190

### LINKED ISSUE #2190: [V5] Verdaccio is not working behind http2 proxy
**Describe the bug**

Verdaccio v5 is not detecting headers passed from reverse proxy, I think it's because of http2 is lowercasing all headers

*log*
```json
{
  "level": 25,
  "time": 1619156769309,
  "pid": 7,
  "hostname": "verdaccio-5bdb8cd95f-6d78j",
  "req":
  {
    "method": "GET",
    "url": "/",
    "query": {},
    "params": {},
    "headers":
    {
      "host": "npm.domain.com",
      "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.9,de;q=0.8",
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "sec-ch-ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
      "sec-ch-ua-mobile": "?0",
      "sec-fetch-dest": "document",
      "sec-fetch-mode": "navigate",
      "sec-fetch-site": "none",
      "sec-fetch-user": "?1",
      "upgrade-insecure-requests": "1",
      "x-forwarded-for": "172.30.2.20",
      "x-forwarded-host": "npm.domain.com",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https",
      "x-forwarded-server": "internal-traefik-6d4789455-hnklc",
      "x-real-ip": "172.30.2.20"
    },
    "remoteAddress": "10.42.235.33",
    "remotePort": 38724
  },
  "ip": "10.42.235.33",
  "msg": "@{ip} requested '@{req.method} @{req.url}'"
}
```

Woraround: override [`VERDACCIO_PUBLIC_URL`](https://github.com/verdaccio/verdaccio/blob/5.x/docs/env.variables.md#verdaccio_public_url)

**To Reproduce**

running verdaccio behind traefik reverse proxy, which is terminating https (http2) connection.

**Expected behavior**

Verdaccio should detect lowercase reverse proxy  headers.

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

### PR DESCRIPTION
**Pull request by juanpicado**
Fix #2190 

It improves how to access to the request headers, instead `req.headers['xxx]` by using `req.get('xxx')` http://expressjs.com/en/api.html#req.get which is does case-insensitive matching.

### CODE REVIEW

File: src/lib/utils.ts [hunk 1]
```diff
@@ -645,7 +645,7 @@ export function getPublicUrl(url_prefix: string = '', req): string {
     if (!isHost(host)) {
       throw new Error('invalid host');
     }
-    const protoHeader = process.env.VERDACCIO_FORWARDED_PROTO ?? HEADERS.FORWARDED_PROTO;
+    const protoHeader = process.env.VERDACCIO_FORWARDED_PROTO?.toLocaleLowerCase() ?? HEADERS.FORWARDED_PROTO?.toLocaleLowerCase();
     const protocol = getWebProtocol(req.get(protoHeader), req.protocol);
```
Comment (semoal) [inline src/lib/utils.ts:649]: probably here, it's more readable to just keep it simple:
```ts
const protoHeader = process.env.VERDACCIO_FORWARDED_PROTO ?? HEADERS.FORWARDED_PROTO
const protocol = getWebProtocol(req.get(protoHeader.toLowerCase()), req.protocol);
```

**Review by semoal — APPROVED** [review]
