### PR TITLE
fix: adds webpack banner plugin to tag bundles with version (#784)

### LINKED ISSUE #784: Add banner plugin to webpack to tag bundle with current version
Currently, There is no build/version information in the webpack bundle. It would be very helpful to find this information. 

https://webpack.js.org/plugins/banner-plugin/

### PR DESCRIPTION
**Pull request by satyamyadav**
**Type:** good first issue

**Description:**  Added webpack banner plugin to tag bundles with current version for web ui production build (yarn run build:webui).
e.g. 
```javascript
/*!
 * 
 *     Name: 1
 *     Generated on: 1529912145630
 *     Package: verdaccio
 *     Version: v3.2.0
 *     License: MIT
 *     
 */
```  

Resolves #784

### CODE REVIEW

**Comment by ayusharma** [comment]
I have two suggestions here:

1. I think we can modify current`getPackageVersion.js` file to get other` package.json` properties.  `getPackageVersion.js` can be renamed to `getPackageJsonInformation.js` and it can export multiple `package.json` properties. Ref: https://github.com/verdaccio/verdaccio/blob/master/tools/getPackageVersion.js 

2. Banner config can be written in `webpack.prod.config.babel.js`.

@juanpicado What do you think?

**Comment by juanpicado** [comment]
Ok, make sense for me @satyamyadav @ayusharma

**Comment by satyamyadav** [comment]
@ayusharma  I was thinking the same, but `getPackageVersion` was used in multiple modules. 
1. It will be good to have  `getPackageJsonInformation` to return content of the package.json as object, and specific values if arguments are provided. 
2. Banner template can be generated in `webpack.prod.config.babel.js`
Also `pkginfo` module is being used can it be used to achieve the same ?

**Comment by ayusharma** [comment]
@satyamyadav Good catch :) Yes. It is used.  You can use `pkgInfo` but there is no need to create any dependency on this package. 

Just use  😉

```
JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json')));
```

**Comment by satyamyadav** [comment]
@ayusharma  is there any benefit of using `JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json')));`  over `require('../package.json')`

**Comment by ayusharma** [comment]
You can use require :
- require is synchronous and only reads the file once, following calls return the result from cache
- If your file does not have a` .json` extension, require will not treat the contents of the file as JSON.

**Comment by juanpicado** [comment]
@satyamyadav @ayusharma perhaps https://github.com/sindresorhus/package-json ?

File: tools/getPackageJson.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  if (!args.length) {
+    return packageJSON;
+  }
+  return args.reduce((out, key) => {
+    out[key] = packageJSON[key];
+    return out;
+  }, {});
+};
+
+module.exports = getPackageJson;
```
Comment (ayusharma) [inline tools/getPackageJson.js]: You can use `export default getPackageJson`

File: tools/webpack.prod.config.babel.js [hunk 2]
```diff
@@ -55,6 +70,6 @@ prodConf.module.rules = baseConfig.module.rules
     Array.isArray(loader.use) && loader.use.find((v) => /css/.test(v.loader.split('-')[0]))
   ).forEach((loader) => {
     loader.use = [MiniCssExtractPlugin.loader].concat(_.tail(loader.use));
-});
+  });
```
Comment (ayusharma) [inline tools/webpack.prod.config.babel.js]: Maybe small indentation issue.

File: tools/getPackageJson.js [hunk 3]
```diff
@@ -0,0 +1,15 @@
+import fs from 'fs';
+import path from 'path';
+
```
Comment (ayusharma) [inline tools/getPackageJson.js]: Good to add JSDOC doc blocks.

File: tools/getPackageJson.js (hunk 1 above)
Comment (juanpicado) [reply tools/getPackageJson.js]: @ayusharma be careful whether that works on Node6

Comment (ayusharma) [reply tools/getPackageJson.js]: Ohh.  Maybe it is fine then... 👍

Comment (juanpicado) [reply tools/getPackageJson.js]: We are not running functional testing on Node6 anymore, because of lack of ES6 support it a huge pain. Node 6 will be only supported for us this year on build pipeline.

File: tools/getPackageJson.js (hunk 3 above)
Comment (satyamyadav) [reply tools/getPackageJson.js]: Sure I will add it.

**Comment by ayusharma** [comment]
You have to rebase your current branch with master.  Tests are fixed now. 👍

**Comment by satyamyadav** [comment]
@ayusharma  I have re-based my branch with master, tests are passing now.

**Comment by ayusharma** [comment]
Thank you so much @satyamyadav for your first contribution to the verdaccio.

**Comment by satyamyadav** [comment]
Thanks @juanpicado  and @ayusharma  for your quick reviews, I will try to be more careful about the small things while raising a pull requests.
