### PR TITLE
fix: correctly check the keepAliveTimeout value, fixes #1352

### LINKED ISSUE #1352: Set config.server.keepAliveTimeout to 0 should disable keep-alive
It seems setting config.server.keepAliveTimeout to 0 doesn't disable keep-alive, but using the default value (5000ms according to the nodejs doc).

https://github.com/verdaccio/verdaccio/blob/e40083a6be4abf1a3539b776d3a4053f484e0002/src/lib/bootstrap.js#L51

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
bug

The following has been addressed in the PR:

*  #1352

**Description:**

This correctly checks the `keepAliveTimeout`.
It is either not in the config at all (= undefined) or not set (= null) or set (0 or greater = number / string).

### CODE REVIEW

**Comment by DanielRuf** [comment]
I will add the tests then (config.spec.js, new server.spec and util file probably and so on).

File: src/lib/bootstrap.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ function startVerdaccio(config: any, cliListen: string, configPath: string, pkgV
         // http
         webServer = http.createServer(app);
       }
-      if (config.server && config.server.keepAliveTimeout) {
+      if (config.server && typeof config.server.keepAliveTimeout !== 'undefined' && config.server.keepAliveTimeout !== 'null') {
```
Comment (juanpicado) [inline src/lib/bootstrap.js]: :-) don't like lodash 👩‍🚀  ?

Comment (DanielRuf) [reply src/lib/bootstrap.js]: lodash, underscore and ithers are mostly too bloated. The current code should be clear enough. No need to make it more abstract or complicated imo.

Comment (juanpicado) [reply src/lib/bootstrap.js]: Agree, but, I admit that lodash was really useful to put the order in the house. Perhaps is a moment to introduce something smaller or homemade that does not force to write too much boilerplate.

**Comment by DanielRuf** [comment]
@juanpicado I am not fully sure about the test files but we can only test it using the CLI or starting the server which calls the bootstrap logic. Quite confusing setup currently.

Let me know if and how I can improve this.

**Comment by juanpicado** [comment]
> Let me know if and how I can improve this.

I have no clear answer yet, but I will think in a strategy on how to test this.

File: test/unit/api/cli.spec.js [hunk 2]
```diff
@@ -42,6 +47,75 @@ describe('startServer via API', () => {
       });
     });
 
+    test('should set keepAliveTimeout to 0 seconds', async (done) => {
+      const store = path.join(__dirname, 'partials/store');
+      const serverName = 'verdaccio-test';
+      const version = '1.0.0';
+      const port = '6100';
+
+      await startServer(config(parseConfigurationFile('server/keepalivetimeout-0')), port, store, version, serverName,
```
Comment (juanpicado) [inline test/unit/api/cli.spec.js]: ahh, you added test :-) cool

**Comment by juanpicado** [comment]
LGTM, the test will help a lot :-) Thanks @DanielRuf
