### PR TITLE
fix: avoid setting body for GET requests

### LINKED ISSUE #3601: Publish new package throw error when uplink set to `https://registry.npmmirror.com`（cnpm registry）
The registry `https://registry.npmmirror.com` will return a 413 status code for a GET request containing a request body, which will cause an error when publishing a new package, resulting in a failure to publish.

On the other hand, a GET request should not contain a request body.

### PR DESCRIPTION
**Pull request by melodyVoid**
When making a GET request to certain uplinks, such as https://registry.npmmirror.com, setting the body field can result in a 413 error. Previously, the code was setting the body field for all requests, including GET requests.

This commit fixes the issue by checking the request method and avoiding setting the body field for GET requests. This ensures that GET requests are not affected by the issue and can be made without error.

Fixes #3601

### CODE REVIEW

File: src/lib/up-storage.ts [hunk 1]
```diff
@@ -228,6 +227,11 @@ class ProxyStorage implements IProxy {
       agentOptions: this.agent_options,
     };
 
+    // GET requests should not have a body, otherwise the request might fail(return 413 status code)
+    if (method.toUpperCase() !== 'GET') {
```
Comment (juanpicado) [inline src/lib/up-storage.ts:231]: great you found a solution, also thanks for the comment, would you mind add some test, here you can star looking at `test/unit/modules/uplinks/up-storage.spec.ts`

**Comment by juanpicado** [comment]
Format is not correct, you can run `yarn format` to fix it.

File: src/lib/up-storage.ts (hunk 1 above)
Comment (melodyVoid) [reply src/lib/up-storage.ts:231]: I'll fix the code format and add some unit tests.

File: src/lib/up-storage.ts [hunk 2]
```diff
@@ -227,11 +228,6 @@ class ProxyStorage implements IProxy {
       agentOptions: this.agent_options,
     };
 
-    // GET requests should not have a body, otherwise the request might fail(return 413 status code)
-    if (method.toUpperCase() !== 'GET') {
-      requestOptions.body = json
-    }
-
```
Comment (melodyVoid) [inline src/lib/up-storage.ts]: I deleted these code, because I found the bug is in [this line](https://github.com/verdaccio/verdaccio/blob/bae430fe24c9bb63dcf7b7b9e5f9f0dbf3f42669/src/lib/up-storage.ts#L157).
I create a new [PR](https://github.com/verdaccio/verdaccio/pull/3647) to fix this bug.

> don't forget update `verdaccio/core`

**Comment by juanpicado** [comment]
@melodyVoid please feel free to update the dependency in your branch

**Comment by melodyVoid** [comment]
> @melodyVoid please feel free to update the dependency in your branch

I updated the dependency, please check it out.

**Review by juanpicado — APPROVED** [review]
Great job @melodyVoid ! LGTM
