### PR TITLE
fix: hydrate template placeholders in JSON log messages

### LINKED ISSUE #2649: JSON logs do not hydrate template placeholders
### Discussed in https://github.com/verdaccio/verdaccio/discussions/2286

<div type='discussions-op-text'>

<sup>Originally posted by **capps1994** June 11, 2021</sup>
We have updated our Verdaccio instance, to 5.1.0 and now logging seems to be not working as expected.

In our logs we see `{"level":25,"time":1623421647904,"pid":8,"hostname":"e643fb945f2c","request":{"method":"GET","url":"/-/verdaccio/packages"},"user":null,"remoteIP":"172.18.0.1","status":304,"bytes":{"in":0,"out":0},"msg":"@{status}, user: @{user}(@{remoteIP}), req: '@{request.method} @{request.url}', bytes: @{bytes.in}/@{bytes.out}"}`

We have the following in our config `logs:`
  `- { type: stdout, format: pretty, level: http }`

Has anything changed?
  </div>
<br>

@juanpicado I was in the process of opening a PR against `master` (for Verdaccio 6) but it looks like the unit tests for `packages/logger` are busted as are a number of other unit tests for other packages. I read the [Contributing Guidelines](https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md) and followed the instructions for [_Running test_](https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#running-test) but continue (even after some troubleshooting) to receive errors:
```text
packages/logger test$ cross-env NODE_ENV=test BABEL_ENV=test jest --runTestsByPath
│ FAIL test/logger.spec.ts
│   ● Test suite failed to run
│     Cannot find module '@verdaccio/core' from 'test/logger.spec.ts'
│     > 1 | import { warningUtils } from '@verdaccio/core';
│         | ^
│       2 |
│       3 | import { logger, setup } from '../src';
│       4 |
│       at Resolver.resolveModule (../../node_modules/.pnpm/jest-resolve@27.3.1/node_modules/jest-resolve/build/resolver.js:324:11)
│       at Object.<anonymous> (test/logger.spec.ts:1:1)
│ -----------|---------|----------|---------|---------|-------------------
│ File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
│ -----------|---------|----------|---------|---------|-------------------
│ All files  |       0 |        0 |       0 |       0 |
│  index.ts  |       0 |        0 |       0 |       0 |
│  logger.ts |       0 |        0 |       0 |       0 | 7-156
│ -----------|---------|----------|---------|---------|-------------------
│ Test Suites: 1 failed, 1 total
│ Tests:       0 total
│ Snapshots:   0 total
│ Time:        1.612 s
│ Ran all test suites within paths .
└─ Failed in 2.4s
packages/plugins/active-directory test$ cross-env NODE_ENV=test BABEL_ENV=test jest
[2 lines collapsed]
│     Cannot find module '@verdaccio/core' from 'tests/active-directory.test.ts'
│       1 | import ActiveDirectory from 'activedirectory2';
│       2 |
│     > 3 | import { HTTP_STATUS } from '@verdaccio/core';
│         | ^
│       4 |
│       5 | import ActiveDirectoryPlugin, { NotAuthMessage } from '../src/active-directory';
│       6 | // eslint-disable-next-line jest/no-mocks-import
│       at Resolver.resolveModule (../../../node_modules/.pnpm/jest-resolve@27.3.1/node_modules/jest-resolve/build/resolver.js:324:11)
│       at Object.<anonymous> (tests/active-directory.test.ts:3:1)
└─ Running...
```

I listed only 2 of the failing packages in the output above (`logger` package included) but there there were a few others with the same exact issue related to *`Cannot find module '@verdaccio/core' from <some_other_package>`*. As mentioned, I spent some time trying to troubleshoot but I'm not intimately familiar with Verdaccio's build process/configuration or `pnpm` in general.

I have a fix for the issue from the discussion but don't want to submit the PR without working unit tests. Any guidance that can be provided would be appreciated. Thanks.

### PR DESCRIPTION
**Pull request by edclement**
Closes #2649
Related to discussion #2286 

This change fixes the issue where the `msg` property in JSON format logs does not have the template placeholders hydrated with values.

**Without this fix**
```text
{"level":25,"time":1636481904624,"pid":133492,"hostname":"workstation","sub":"in","request":{"method":"GET","url":"/-/verdaccio/packages"},"user":null,"remoteIP":"127.0.0.1","status":200,"bytes":{"in":0,"out":3},"msg":"@{status}, user: @{user}(@{remoteIP}), req: '@{request.method} @{request.url}', bytes: @{bytes.in}/@{bytes.out}"}
```

**With this fix**
```
{"level":25,"time":1636482057018,"pid":135963,"hostname":"workstation","sub":"in","request":{"method":"GET","url":"/-/verdaccio/packages"},"user":null,"remoteIP":"127.0.0.1","status":304,"bytes":{"in":0,"out":0},"msg":"304, user: null(127.0.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/0"}
```

This is my first contribution and I believe I properly followed the [Contributing Guidelines](https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#contributing-guidelines). If I missed something please let me know.

Unit tests were not added since the code changes effect `pino` logger configuration. There are currently no _direct_ unit tests for `fillinMsgTemplate` from the `@verdaccio/logger-prettify` package.

### CODE REVIEW

File: packages/logger-prettify/src/index.ts [hunk 1]
```diff
@@ -1,18 +1,20 @@
...
+
 export type PrettyFactory = (param) => string;
 
 /*
  options eg:
  { messageKey: 'msg', levelFirst: true, prettyStamp: false }
  */
 
-module.exports = function prettyFactory(options: PrettyOptionsExtended): PrettyFactory {
+export default function prettyFactory(options: PrettyOptionsExtended): PrettyFactory {
```
Comment (Splaktar) [inline packages/logger-prettify/src/index.ts:13]: I have not seen anything but problems with default imports. Is this necessary or part of some new Verdaccio guidelines?

Comment (juanpicado) [reply packages/logger-prettify/src/index.ts:13]: > I have not seen anything but problems with default imports.
Could you share some? I'm curious. No strict guidelines on this, as long is ES6 syntax we are fine.

Comment (juanpicado) [reply packages/logger-prettify/src/index.ts:13]: Just for context, Pino expect `default`, eg: https://github.com/pinojs/pino-pretty/blob/master/index.js#L217

**Review by juanpicado — APPROVED** [review]
LGTM, great fix 🚀 

Thanks for the detailed PR description.

About test, not need it now, still lacky will be added soon.

File: packages/logger-prettify/src/index.ts (hunk 1 above)
Comment (edclement) [reply packages/logger-prettify/src/index.ts:13]: @Splaktar - it was technically the default export prior but used the commonJS syntax. I was aiming to try to change/refactor as little code as possible with this PR. Doing a _rough_ search within the Verdaccio source code I see close to 200 other uses of `export default ...` so it aligns with the current coding style/conventions used within Verdaccio.

**Comment by edclement** [comment]
@juanpicado - just confirming that you don't need anything else from me in order to get this merged?

**Comment by juanpicado** [comment]
I was just giving a chance to @Splaktar reply. LGTM by far. :) I didn't want to be rude.

**Comment by juanpicado** [comment]
Ok :) we can follow discussing here in any case.

File: packages/logger-prettify/src/index.ts (hunk 1 above)
Comment (Splaktar) [reply packages/logger-prettify/src/index.ts:13]: It's probably fine in NodeJS apps, most issues I've seen with them are in web apps due to webpack and bundle splitting, etc.
