### PR TITLE
Plugin loader with logs

### LINKED ISSUE #321: Plugin loader display loading state on logger for each plugin used on conf file
#### My reason:

There is no way to know whether any plugin has been loaded. On Docker containers would be really helpful see something in the log.

The expected behaviour would display any kind of verbose about whether the plugin has been loaded or has failed on load.

#### Steps to reproduce:

The following example is an intent to integrate [verdaccio-ldap](https://github.com/Alexandre-io/verdaccio-ldap) plugin. 
https://github.com/verdaccio/docker-examples/tree/master/ldap-verdaccio

####  App Version:	

All

####  Config file:	
```
storage: /verdaccio/storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://verdaccio:389"
      bindDn: "dc=openstack,dc=org"
      bindCredentials: ""
      searchBase: "dc=openstack,dc=org"
      searchFilter: "(cn={{username}})"
      cache: False
      tlsOptions:
        rejectUnauthorized: False

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
  #- {type: file, path: verdaccio.log, level: info}

listen:
  - 0.0.0.0:4873
```

#### Additional information:

 - Container:
   - I use local environment
   - I develop / deploy using Docker.

#### Additional verbose log:

```
➜ docker-compose up
Starting ldapverdaccio_verdaccio_1 ... 
Starting ldapverdaccio_verdaccio_1 ... done
Starting ldapverdaccio_ldapserver_1 ... 
Starting ldapverdaccio_ldapserver_1 ... done
Attaching to ldapverdaccio_verdaccio_1, ldapverdaccio_ldapserver_1
ldapserver_1  | 59b6f5e0 @(#) $OpenLDAP: slapd  (Ubuntu) (May 25 2015 13:12:01) $
ldapserver_1  | 	buildd@toyol:/build/buildd/openldap-2.4.31/debian/build/servers/slapd
ldapserver_1  | 59b6f5e0 hdb_db_open: database "dc=nodomain": unclean shutdown detected; attempting recovery.
ldapserver_1  | 59b6f5e0 hdb_db_open: database "dc=openstack,dc=org": unclean shutdown detected; attempting recovery.
ldapserver_1  | 59b6f5e1 slapd starting
ldapserver_1  | 59b6f5e1 bdb(dc=nodomain): BDB0060 PANIC: fatal region error detected; run recovery
verdaccio_1   |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio_1   |  warn --- http address - http://0.0.0.0:4873/ - verdaccio/2.3.6
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/static/main.8c939cd13e9334bbcf2d.js', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/static/style.8410f14de467c42d2f6c14c7df197f3f.css', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/static/logo.png', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/0
```

### PR DESCRIPTION
**Pull request by ayusharma**
Plugin loader improvement with logger

**Type:** Improvement

The following has been addressed in the PR:

*  There is a related issue
*  Unit or Functional tests are included in the PR.

**Description:**

Resolves #321 

* I tried to improve plugin loading system using promise and added logs functionality.

### CODE REVIEW

**Comment by ayusharma** [comment]
@juanpicado Please let me know your thoughts on the changes in this PR.

**Comment by juanpicado** [comment]
@ayusharma sorry I'm not available these days, I'll take care of reviews next week.

**Comment by juanpicado** [comment]
I've just reviewed the code but not deeply. Does it compatible with current plugins?

**Comment by ayusharma** [comment]
It was compatible as I tested it with htpasswd, bitbucket-auth plugin. I am confused in a situation.

At line https://github.com/verdaccio/verdaccio/blob/9ff71606409d2cb9899aae9c4b8ca39445a750eb/src/lib/plugin-loader.js#L58,

We were throwing an error if specified plugin is not found but in my PR I made a promise and rejected it so I can show in logs. I am not stopping app execution as before. 

Is it a good behavior ?

**Comment by juanpicado** [comment]
Let me try both behaviours and I'll let you know

File: src/lib/plugin-loader.js [hunk 1]
```diff
@@ -1,7 +1,8 @@
 'use strict';
 
 const Path = require('path');
-
+const logger = require('./logger');
+logger.setup(); // default setup
```
Comment (juanpicado) [inline src/lib/plugin-loader.js]: We cannot do setup twice, the first setup is on `cli.js`

File: src/lib/plugin-loader.js [hunk 2]
```diff
@@ -31,47 +32,71 @@ function try_load(path) {
...
+      }
 
-    if (plugin === null) {
-      throw Error('"' + p + '" plugin not found\ntry "npm install verdaccio-' + p + '"');
-    }
+      if (plugin === null) {
+        reject('' + p + ' plugin not found. try "npm install verdaccio-' + p + '"');
+      }
 
-    if (typeof(plugin) !== 'function') {
```
Comment (juanpicado) [inline src/lib/plugin-loader.js]: Answering your question, I am afraid if we don't force to stop the app we might allow a usage of corrupted plugins. I guess if one plugin does not work we have to be strict, otherwise, it will lead us to wrong behaviors that people won't understand. We need to find a better solution

**Comment by ayusharma** [comment]
I think I have complicated the flow. My PR is changing a lot of code if I made the plugin flow using promises. 

So If I add logger just before the throw handler, It will add it to the logger.

https://github.com/verdaccio/verdaccio/blob/fb8f4cc4c291768cbcf1fb94a726043e4957bca9/src/lib/plugin-loader.js#L58

We can place a logger before every throw to log before app stops. and one before the return statement of the map function. Please let me know your thoughts on this.

**Comment by ayusharma** [comment]
@juanpicado Please suggest me on this.

**Comment by juanpicado** [comment]
@ayusharma sorry I didn't reply. I don't understand your question.

**Comment by ayusharma** [comment]
@juanpicado I changed the PR and add logger while we are loading plugins. In my previous PR, I did it in a complex way. Please correct me If I am doing it wrong.

**Comment by juanpicado** [comment]
Looks good to me 👍  . Nice feedback to know which plugins are being loaded.

```
Users/user/.nvm/versions/node/v8.3.0/bin/node /Users/user/projects/verdaccio.master.git/bin/verdaccio --listen 5555
 warn --- config file  - /Users/user/.config/verdaccio/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- http address - http://localhost:5555/ - verdaccio/2.5.1
```

**Comment by juanpicado** [comment]
If you are agreed. I'll merge.

**Comment by juanpicado** [comment]
You need to rebase first.

**Comment by juanpicado** [comment]
Please, use this format in the commit. `fix: xxxx`. It makes much much easier releases.

File: src/lib/plugin-loader.js [hunk 3]
```diff
@@ -55,19 +56,22 @@ function load_plugins(config, plugin_configs, params, sanity_check) {
...
     }
 
     plugin = plugin(plugin_configs[p], params);
 
     if (plugin === null || !sanity_check(plugin)) {
+      Logger.logger.error({content: p}, '@{content} doesn\'t look like a valid plugin');
       throw Error('"' + p + '" doesn\'t look like a valid plugin');
     }
-
+    Logger.logger.warn({content: p}, 'Plugin successfully loaded: @{content}');
```
Comment (juanpicado) [inline src/lib/plugin-loader.js]: One more thing, perhaps `warn` is too aggressive. Users might think there is an error. Perhaps we should use `info` instead?

Comment (ayusharma) [reply src/lib/plugin-loader.js]: Yes,  I've updated the PR.

**Comment by juanpicado** [comment]
Perfect ! :) Thanks
