### PR TITLE
fix: fixed user creation endpoint to properly import groups

### LINKED ISSUE #1426: callback for auth.authenticate returns a user, not a group.
**Describe the bug**
When attempting to publish a package, auth.authenticate() is called in order to confirm that the user belongs to a group with permissions to publish. This function calls back with a user object but the code found in `/src/api/endpoint/api/user.ts` expects a group.  

**To Reproduce**
There might be other ways to reproduce but these are the steps which i have reliably used:
- in the configuration, create a scoped package `@myscope` with publishing permissions tied to a custom group `mygroup`
- have an auth plugin successfully authenticate and return the group `mygroup`. I used the verdaccio-activedirectory plugin but any plugin supporting groups should work.
- log in to npm and attempt to publish a scoped package `@myscope/testpackage`. It will return a 403 error.

**Expected behavior**
Users who authenticate against a group should be permitted to have the permissions granted by it.

**Configuration File**
I'm only illustrating how I have packages
```
packages:
  '@myscope/*':
    access: $authenticated
    publish: mygroup
    unpublish: mygroup
```

**Additional context**

As stated above, the root cause of this issue is that the `PUT` request to publish a package is incorrectly handling the callback from `auth.authenticate()` (found here: https://github.com/verdaccio/verdaccio/blob/66f4197236d9d71af149314aae15102b336f45e1/src/api/endpoint/api/user.ts#L26).

### PR DESCRIPTION
**Pull request by devnill**
This is a fix for this: https://github.com/verdaccio/verdaccio/issues/1426

Root cause is that the `auth.authenticate()` method calls back with the arguments `(err, user)` but the method to add a user is expecting `(err, groups)`.

I'd like to also add tests to this PR but i'm not sure the best way to go about it. I didn't see an interface for this kind of callback in the monorepo or flow-types. Is there a preferred method to approach this kind of issue?

Resolves #1426

### CODE REVIEW

File: src/api/endpoint/api/user.ts [hunk 1]
```diff
@@ -23,13 +23,13 @@ export default function(route: Router, auth: IAuth, config: Config): void {
...
     if (_.isNil(remoteName) === false && _.isNil(name) === false && remoteName === name) {
-      auth.authenticate(name, password, async function callbackAuthenticate(err, groups): Promise<void> {
+      auth.authenticate(name, password, async function callbackAuthenticate(err, user): Promise<void> {
         if (err) {
           logger.trace({ name, err }, 'authenticating for user @{username} failed. Error: @{err.message}');
           return next(ErrorCode.getCode(HTTP_STATUS.UNAUTHORIZED, API_ERROR.BAD_USERNAME_PASSWORD));
         }
 
-        const restoredRemoteUser: RemoteUser = createRemoteUser(name, groups);
+        const restoredRemoteUser: RemoteUser = createRemoteUser(name, user.groups || []);
```
Comment (juanpicado) [inline src/api/endpoint/api/user.ts]: ` || []` is not need it, but also not harmful, there is a check within the `createRemoteUser` method. 

```
const isGroupValid: boolean = Array.isArray(pluginGroups);
  const groups = (isGroupValid ? pluginGroups : []).concat([ROLES.$ALL, ROLES.$AUTH, ROLES.DEPRECATED_ALL, ROLES.DEPRECATED_AUTH, ROLES.ALL]);
```
