### PR TITLE
fix(middleware): properly derive the html cache key

### LINKED ISSUE #5195: Web UI html is cached inproperly
**Your Environment**
  
 * **verdaccio version**: 6.1.2
 * **os**: docker on windows (wsl2)

When the web ui html is created from a template, different base URLs are used depending on the `Host` request header, but this is not taken into account when caching the html.

Probably related to #4086, #4129, #5128, 

**To Reproduce**

1. Start verdaccio server with the default settings (`config.web.html_cache = true`)
2. Open `localhost:8000` in your browser
3. Open `127.0.0.1:8000` in your browser

If you check the html, you should see a reference to the resource from `localhost:8000/-/static/...`, even though you are accessing from `127.0.0.1:8000`.

**Expected behavior**

html will be rendered correctly.

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇

### PR DESCRIPTION
**Pull request by omasakun**
Include template rendering options that change depending on the request header in the cache key

Fixes #5195

### CODE REVIEW

File: packages/middleware/src/middlewares/web/utils/renderHTML.ts [hunk 1]
```diff
@@ -132,8 +133,20 @@ export default function renderHTML(
 
   let webPage;
 
+  let cacheKey =
```
Comment (mbtools) [inline packages/middleware/src/middlewares/web/utils/renderHTML.ts:136]: Let's change this so it's more future proof (if options change or are added):

```js
  const cacheKey = `template:${stringToMD5(JSON.stringify(options))}`;
```

**Review by mbtools — CHANGES_REQUESTED** [review]
Thanks for the PR! The failing test is not your fault. It's fixed in #5197. 

Please add a changeset as described here:

https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#adding-a-changeset-changeset

File: packages/middleware/src/middlewares/web/utils/renderHTML.ts (hunk 1 above)
Comment (omasakun) [reply packages/middleware/src/middlewares/web/utils/renderHTML.ts]: Changed the cache key to be calculated from the entire options
Also, a changeset is added

**Comment by juanpicado** [comment]
FYI: I'm testing Copilot as reviewer, just take them as suggestions.

**Comment by mbtools** [comment]
This is done for every page load. Do we have to check the performance impact?

**Comment by omasakun** [comment]
I think the options object is so small that the time required for JSON serialization and md5 calculation should be short enough, especially since the current code already seems to call `stringToMD5` on the entire response body for etag calculation by the final middleware for every request.

However, lru-cache seemed to have no performance problems with long strings as keys ([bench](https://github.com/isaacs/node-lru-cache/tree/main/benchmark#:~:text=longstr)), so I removed the stringToMD5 call.

Example of an options object (338 chars):

``` json
{"darkMode":false,"basename":"/","base":"http://localhost:8000/","primaryColor":"#4b5e40","version":"8.0.0-next-8.15","logo":"","logoDark":"","favicon":"","flags":{"searchRemote":true,"changePassword":false},"login":true,"pkgManagers":["yarn","pnpm","npm"],"title":"Verdaccio","scope":"","language":"en-US","hideDeprecatedVersions":false}
```

**Review by mbtools — APPROVED** [review]
LGTM

**Review by juanpicado — APPROVED** [review]
