### PR TITLE
fix: tarball urls for web/package (fix #1714)

### LINKED ISSUE #1714: Wrong scheme in tarball link for UI
**Describe the bug**

When verdaccio is accessed via HTTPS, dist.tarball urls are returned with wrong scheme (http instead of https) to UI (api uri: `/-/verdaccio/packages`)

**To Reproduce**

1. Serve verdaccio via https
2. Try to download a package tarball

**Expected behavior**
Tarball is downloaded

**Actual behavior**
Tarball tries to be downloaded via http, which violates CSP (`connect-src self`).

**Environment information**

verdaccio --info: (cpu removed)
Environment Info:
  System:
    OS: Linux 4.19 Alpine Linux
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm

verdaccio version: 4.4.2

It's running in kubernetes cluster from a custom image based on `verdaccio:4.4.2` and exposed via ingress.

**Additional information:**
I think this is not UI bug but rather backend bug since tarball url shown by `npm show` has correct scheme (https).

### PR DESCRIPTION
**Pull request by stek29**
**Type:** bug

The following has been addressed in the PR:
tarball links not being preprocessed on `/-/packages` web api endpoint

*  Unit or Functional tests were not changed

**Resolves:** #1714

### CODE REVIEW

File: src/api/web/endpoint/package.ts [hunk 1]
```diff
@@ -70,6 +71,10 @@ function addPackageWebApi(route: Router, storage: IStorageHandler, auth: IAuth,
             logger.logger.error({ name: pkg.name, error: err }, 'permission process for @{name} has failed: @{error}');
             throw err;
           }
+
```
Comment (juanpicado) [inline src/api/web/endpoint/package.ts]: Unfortunately, this won't work as you expect.  First, the `pkgCopy` is checking permissions above, so, whatever action is needed it must be within the `try/catch`. Furthermore, `dist` is a property that belongs to `Version` rather `Package`.

Comment (stek29) [reply src/api/web/endpoint/package.ts]: @juanpicado I've tested it. Packages gotten from storage do have dist property, and i'm not sure if they do have a version.

**Comment by stek29** [comment]
@juanpicado nope, I can't do that -- I need pkgCopy[].dist.tarball to be updated, not pkgCopy[].versions[].dist.tarball.

File: src/api/web/endpoint/package.ts [hunk 2]
```diff
@@ -70,6 +71,10 @@ function addPackageWebApi(route: Router, storage: IStorageHandler, auth: IAuth,
...
+          if (!_.isNil(pkgCopy.dist) && !_.isNull(pkgCopy.dist.tarball)) {
+            pkgCopy.dist.tarball = getLocalRegistryTarballUri(pkgCopy.dist.tarball, pkg.name, req, config.url_prefix);
```
Comment (juanpicado) [inline src/api/web/endpoint/package.ts]: This should be inside of the `try catch` block like

```
            if (await checkAllow(pkg.name, req.remote_user)) {
              if (config.web) {
                   if (!_.isNil(pkgCopy.dist) && !_.isNull(pkgCopy.dist.tarball)) {
                          pkgCopy.dist.tarball = getLocalRegistryTarballUri(pkgCopy.dist.tarball, pkg.name, req, config.url_prefix);
                   }
                  pkgCopy.author.avatar = generateGravatarUrl(pkgCopy.author.email, config.web.gravatar);
              }
              permissions.push(pkgCopy);
            }
```

**Comment by juanpicado** [comment]
> @juanpicado nope, I can't do that -- I need pkgCopy[].dist.tarball to be updated, not pkgCopy[].versions[].dist.tarball.

Yea, the Typescript type `Package` is misleading and you are right, just check what I wrote above and I guess we are done, there is no test for this specific thing.

File: src/api/web/endpoint/package.ts [hunk 3]
```diff
@@ -66,6 +67,10 @@ function addPackageWebApi(route: Router, storage: IStorageHandler, auth: IAuth,
               }
               permissions.push(pkgCopy);
             }
+
+            if (!_.isNil(pkgCopy.dist) && !_.isNull(pkgCopy.dist.tarball)) {
```
Comment (juanpicado) [inline src/api/web/endpoint/package.ts]: Sorry, perhaps I did not explain good enough, but this code has to be inside of the `if (await checkAllow(pkg.name, req.remote_user)) {` block, otherwise we will mutate all packages, we don't want that, we will retrieve only those user is allowed to see, plus, it has to happen before`permissions.push(pkgCopy);`. Hopefully now is more clear, let me know if you have questions.

Comment (stek29) [reply src/api/web/endpoint/package.ts]: @juanpicado oh, I see

**Comment by juanpicado** [comment]
Thanks @stek29 great stuff ! 👏
