### PR TITLE
fix(test): replaces LocaleString with date-nfs/format

### LINKED ISSUE #542: Test fails when locale is in spanish
#### My reason:

I'm trying to run the tests and a few fails due to locale being in spanish.

#### Steps to reproduce:
I am using **Fedora 27** and using **es_NI.utf8** as locale.

```
 FAIL  test/webui/components/PackageSidebar/lastsync.spec.js
  <PackageSidebar /> : <LastSync />
    ✕ should load the component and check getters: lastUpdate, recentReleases with package data (98ms)
    ✕ should load the LastSync component and match snapshot (58ms)

  ● <PackageSidebar /> : <LastSync /> › should load the component and check getters: lastUpdate, recentReleases with package data

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "Dec 14, 2017, 3:43 PM"
    Received:
      "14 Dec 2017, 3:43 pm"

      24 |       { time: 'Nov 8, 2017, 10:47 PM', version: '2.6.6' }
      25 |     ];
    > 26 |     expect(instance.lastUpdate).toEqual('Dec 14, 2017, 3:43 PM');
      27 |     expect(instance.recentReleases).toEqual(result);
      28 |   });
      29 | 
      
      at Object.it (test/webui/components/PackageSidebar/lastsync.spec.js:26:33)

### PR DESCRIPTION
**Pull request by ayusharma**
**Type:**

The following has been addressed in the PR:

*  There is a related issue #542 
*  Unit or Functional tests are included in the PR

**Description:**
- Replaces `toLocaleString` with `date-nfs/format`
- Runs every test in UTC timezone.

### CODE REVIEW

File: src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx [hunk 1]
```diff
@@ -19,14 +19,18 @@ export default class LastSync extends React.Component {
       }
     });
 
-    return lastUpdate ? datetime(lastUpdate) : '';
+    const datetime = format(new Date(lastUpdate), 'MMM D, YYYY, h:mm A');
```
Comment (juanpicado) [inline src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: Create a common constant of this format in a common place `'MMM D, YYYY, h:mm A'`

File: src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx [hunk 2]
```diff
@@ -19,14 +19,18 @@ export default class LastSync extends React.Component {
...
   }
 
   get recentReleases() {
     let recentReleases = Object.keys(this.props.packageMeta.time).map((version) => {
+      const datetime = format(new Date(this.props.packageMeta.time[version]),
+        'MMM D, YYYY, h:mm A');
       return {
         version,
-        time: datetime(this.props.packageMeta.time[version])
+        time: datetime
```
Comment (juanpicado) [inline src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: use `time` instead `datetime` and then return `{version, time}`

File: src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx (hunk 1 above)
Comment (Meeeeow) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: I don't think this is a good idea for a international project. In my country, we use `YYYY/MM/DD HH:mm:ss` not `MMM D, YYYY, h:mm A`, it's really hard to read for some people

File: src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx (hunk 2 above)
Comment (Meeeeow) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: `let` or `const`?
Which one should be used in this project? @juanpicado 

---

Also you can use shorthand for `time: datetime` by change variable name to `time`

Comment (juanpicado) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: Yeah, that's I meant

File: src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx (hunk 1 above)
Comment (juanpicado) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: What could we use?

Comment (Meeeeow) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: @juanpicado Follow browser or system settings
```js
(new Date(timestamp).toLocaleString())
```

Comment (juanpicado) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: But test might be run on a different system, we need to avoid side effects on a test environment.

File: src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx (hunk 2 above)
Comment (juanpicado) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: @Meeeeow rule for me is simple, `const` whether the variable won't change. Something else `let`.

File: src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx (hunk 1 above)
Comment (ayusharma) [reply src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx]: @Meeeeow the current implementation replaces the (new Date(timestamp).toLocaleString()) in different os environments.

File: package.json [hunk 3]
```diff
@@ -147,10 +148,10 @@
     "prepublish": "in-publish && npm run build:webui && npm run code:build || not-in-publish",
     "flow": "flow",
     "pretest": "npm run code:build",
-    "test": "cross-env NODE_ENV=test BABEL_ENV=test jest --maxWorkers 2",
+    "test": "cross-env NODE_ENV=test BABEL_ENV=test TZ=UTC jest --maxWorkers 2",
```
Comment (ayusharma) [inline package.json]: @juanpicado I am passing `TZ=utc` env variable to run tests in UTC.
